services:
  - type: web
    name: fyp2
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
