services:
  - type: web
    name: utar-chatbot
    env: python
    plan: standard
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 180 --workers 1 --threads 2 --preload"
